### ISSUE TITLE
Files not found

### ISSUE THREAD

**Issue by bartkessels** [bartkessels/simpleconvert#6]
When converting a file it says that it can't find the `ffmpeg` module.

I've debugged a little bit and it seems that ffmpeg cannot find the specified files.

__Error message:__

```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/site-packages/simpleconvert/SimpleconvertWindow.py", line 175, in convert_file
    ffmpeg.run(stream)
  File "/usr/lib/python3.6/site-packages/ffmpeg_python-0.1.9-py3.6.egg/ffmpeg/_run.py", line 146, in run
    _subprocess.check_call(args)
  File "/usr/lib64/python3.6/subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python3.6/subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'
```

**Comment by bartkessels** [comment]
Got this because `ffmpeg` wasn't installed, updated readme to reflect this 1c5d2cc
